<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>Bielarusizatar_Valheim</AssemblyName>
    <RootNamespace>Bielarusizatar.Valheim</RootNamespace>
    <Version>2.0.0</Version>
    <OutputPath>$(MSBuildProjectDirectory)/../../plugins/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <Nullable>disable</Nullable>
    <NoWarn>CS1701;CS1702;CS1705</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Plugin.cs" />
  </ItemGroup>
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>/home/alek/.steam/steam/steamapps/common/Valheim/BepInEx/core/BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>/home/alek/.steam/steam/steamapps/common/Valheim/BepInEx/core/0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>/home/alek/.steam/steam/steamapps/common/Valheim/valheim_Data/Managed/UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>/home/alek/.steam/steam/steamapps/common/Valheim/valheim_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>/home/alek/.steam/steam/steamapps/common/Valheim/valheim_Data/Managed/UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>/home/alek/.steam/steam/steamapps/common/Valheim/valheim_Data/Managed/UnityEngine.TextCoreFontEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreTextEngineModule">
      <HintPath>/home/alek/.steam/steam/steamapps/common/Valheim/valheim_Data/Managed/UnityEngine.TextCoreTextEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>/home/alek/.steam/steam/steamapps/common/Valheim/valheim_Data/Managed/Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>/home/alek/.steam/steam/steamapps/common/Valheim/valheim_Data/Managed/assembly_valheim.dll</HintPath>
    </Reference>
    <Reference Include="Jotunn">
      <HintPath>/home/alek/.steam/steam/steamapps/common/Valheim/BepInEx/plugins/Jotunn.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Update="@(Reference)">
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>